"""Added date_created to job_descriptions

Revision ID: 132c8d55c67a
Revises: a330c3b37e07
Create Date: 2025-03-24 11:24:57.211627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132c8d55c67a'
down_revision: Union[str, None] = 'a330c3b37e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'date_created')
    # ### end Alembic commands ###
