"""Add text_content to Resume

Revision ID: 27f23a0d9943
Revises: 469c4f9231e5
Create Date: 2025-04-21 16:34:11.695731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f23a0d9943'
down_revision: Union[str, None] = '469c4f9231e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('text_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'text_content')
    # ### end Alembic commands ###
