"""Add skills, designation, total_experience to applicants

Revision ID: 406fecc6435a
Revises: 7920caeb58fe
Create Date: 2025-03-19 16:32:24.701054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406fecc6435a'
down_revision: Union[str, None] = '7920caeb58fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('applicants', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('applicants', sa.Column('total_experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicants', 'total_experience')
    op.drop_column('applicants', 'designation')
    op.drop_column('applicants', 'skills')
    # ### end Alembic commands ###
