"""Add missing fields to Applicant

Revision ID: 469c4f9231e5
Revises: 848b7c6cbb19
Create Date: 2025-04-21 16:29:38.575826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469c4f9231e5'
down_revision: Union[str, None] = '848b7c6cbb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('applicants', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('applicants', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('applicants', sa.Column('total_experience', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicants', 'total_experience')
    op.drop_column('applicants', 'designation')
    op.drop_column('applicants', 'skills')
    op.drop_column('applicants', 'phone')
    # ### end Alembic commands ###
