"""Updated job descriptions, applicants, and evaluations

Revision ID: 4cd233a6c98e
Revises: d5e0ddcb73ed
Create Date: 2025-03-24 11:41:32.112537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd233a6c98e'
down_revision: Union[str, None] = 'd5e0ddcb73ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
