"""Add date_created to job_descriptions

Revision ID: 7fa330c0fbda
Revises: 4cd233a6c98e
Create Date: 2025-03-24 11:58:31.631820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa330c0fbda'
down_revision: Union[str, None] = '4cd233a6c98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
