"""Updated job descriptions, applicants, and evaluations

Revision ID: a330c3b37e07
Revises: d5f12f9225a7
Create Date: 2025-03-24 10:15:33.723838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a330c3b37e07'
down_revision: Union[str, None] = 'd5f12f9225a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    "applicants",
    "skills",
    type_=sa.JSON,
    existing_type=sa.TEXT,
    postgresql_using="skills::json"
)

    op.alter_column('candidate_evaluations', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('job_descriptions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('job_descriptions', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('job_descriptions', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'location')
    op.drop_column('job_descriptions', 'skills')
    op.drop_column('job_descriptions', 'status')
    op.alter_column('candidate_evaluations', 'score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('applicants', 'skills',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
