"""Fix job_description_id FK and resume relation

Revision ID: b1233b57dcce
Revises: 84025d13e75d
Create Date: 2025-04-21 13:04:46.043231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1233b57dcce'
down_revision: Union[str, None] = '84025d13e75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('status', sa.String(), nullable=False, server_default='Open'))
    op.add_column('resumes', sa.Column('job_description_id', sa.Integer(), nullable=True))
    op.alter_column('resumes', 'parsed_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'resumes', 'job_descriptions', ['job_description_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.alter_column('resumes', 'parsed_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('resumes', 'job_description_id')
    op.drop_column('job_descriptions', 'status')
    # ### end Alembic commands ###
