"""Updated job descriptions, applicants, and evaluations

Revision ID: d5e0ddcb73ed
Revises: a3adf77cfffe
Create Date: 2025-03-24 11:38:07.859691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e0ddcb73ed'
down_revision: Union[str, None] = 'a3adf77cfffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
