"""update user model

Revision ID: dcfab34dc073
Revises: 
Create Date: 2025-04-27 09:47:55.675084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcfab34dc073'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_evaluations', sa.Column('evaluation_duration', sa.Float(), nullable=True))
    op.add_column('candidate_evaluations', sa.Column('evaluation_start_time', sa.DateTime(), nullable=True))
    op.alter_column('candidate_evaluations', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('candidate_evaluations', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('candidate_evaluations', 'hr_manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('candidate_evaluations', 'comments',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('candidate_evaluations_resume_id_fkey', 'candidate_evaluations', type_='foreignkey')
    op.drop_constraint('candidate_evaluations_hr_manager_id_fkey', 'candidate_evaluations', type_='foreignkey')
    op.drop_constraint('candidate_evaluations_job_id_fkey', 'candidate_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_evaluations', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'candidate_evaluations', 'users', ['hr_manager_id'], ['id'])
    op.create_foreign_key(None, 'candidate_evaluations', 'job_descriptions', ['job_id'], ['id'])
    op.drop_column('candidate_evaluations', 'interview_date')
    op.drop_column('candidate_evaluations', 'offer_details')
    op.drop_column('candidate_evaluations', 'interview_notes')
    op.drop_column('candidate_evaluations', 'rejection_reason')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('candidate_evaluations', sa.Column('rejection_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('candidate_evaluations', sa.Column('interview_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('candidate_evaluations', sa.Column('offer_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('candidate_evaluations', sa.Column('interview_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'candidate_evaluations', type_='foreignkey')
    op.drop_constraint(None, 'candidate_evaluations', type_='foreignkey')
    op.drop_constraint(None, 'candidate_evaluations', type_='foreignkey')
    op.create_foreign_key('candidate_evaluations_job_id_fkey', 'candidate_evaluations', 'job_descriptions', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('candidate_evaluations_hr_manager_id_fkey', 'candidate_evaluations', 'users', ['hr_manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('candidate_evaluations_resume_id_fkey', 'candidate_evaluations', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.alter_column('candidate_evaluations', 'comments',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('candidate_evaluations', 'hr_manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('candidate_evaluations', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('candidate_evaluations', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('candidate_evaluations', 'evaluation_start_time')
    op.drop_column('candidate_evaluations', 'evaluation_duration')
    # ### end Alembic commands ###
