"""Updated schema for better resume-job matching

Revision ID: de5c7cb2444a
Revises: 55a2e74870f8
Create Date: 2025-03-19 21:30:13.579224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5c7cb2444a'
down_revision: Union[str, None] = '55a2e74870f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_evaluations', sa.Column('job_id', sa.Integer(), nullable=True))
    op.drop_constraint('candidate_evaluations_job_description_id_fkey', 'candidate_evaluations', type_='foreignkey')
    op.drop_constraint('candidate_evaluations_resume_id_fkey', 'candidate_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_evaluations', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'candidate_evaluations', 'job_descriptions', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_column('candidate_evaluations', 'job_description_id')
    op.add_column('resumes', sa.Column('job_id', sa.Integer(), nullable=True))
    op.drop_constraint('resumes_applicant_id_fkey', 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'applicants', ['applicant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'resumes', 'job_descriptions', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key('resumes_applicant_id_fkey', 'resumes', 'applicants', ['applicant_id'], ['id'])
    op.drop_column('resumes', 'job_id')
    op.add_column('candidate_evaluations', sa.Column('job_description_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'candidate_evaluations', type_='foreignkey')
    op.drop_constraint(None, 'candidate_evaluations', type_='foreignkey')
    op.create_foreign_key('candidate_evaluations_resume_id_fkey', 'candidate_evaluations', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key('candidate_evaluations_job_description_id_fkey', 'candidate_evaluations', 'job_descriptions', ['job_description_id'], ['id'])
    op.drop_column('candidate_evaluations', 'job_id')
    # ### end Alembic commands ###
